apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-configurator
spec:
  selector:
    matchLabels:
      app: node-configurator
  template:
    metadata:
      labels:
        app: node-configurator
    spec:
      hostPID: true
      terminationGracePeriodSeconds: 30
      initContainers:
{{- if .Values.custom_certs.enabled }}
        - name: copy-custom-certs-to-host
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "mkdir-p /host/ca-certs/node-configurator; cp -f /configmaps/custom-certs/* /host/ca-certs/node-configurator" ]
          image: {{ .Values.nsenter.image }}:{{ .Values.nsenter.tag }}
          imagePullPolicy: {{ .Values.nsenter.pullPolicy }}
          resources:
{{ toYaml .Values.nsenter.resources | trim | indent 12 }}
          volumeMounts:
          - name: host-ca-certs
            mountPath: /host/ca-certs
            readOnly: false
          - name: configmap-custom-certs
            mountPath: /configmaps/custom-certs
            readOnly: true
        - name: udpate-ca-certificates-on-host
          command: ["/nsenter", "--all", "--target=1", "sh", "-c", "/usr/sbin/update-ca-certificates"]
          image: {{ .Values.nsenter.image }}:{{ .Values.nsenter.tag }}
          imagePullPolicy: {{ .Values.nsenter.pullPolicy }}
          resources:
{{ toYaml .Values.nsenter.resources | trim | indent 12 }}
          securityContext:
            privileged: true
{{- end }}
        - name: restart-docker-daemon
          command: ["/nsenter", "--all", "--target=1", "sh", "-c", "systemctl restart docker"]
          image: {{ .Values.nsenter.image }}:{{ .Values.nsenter.tag }}
          imagePullPolicy: {{ .Values.nsenter.pullPolicy }}
          resources:
{{ toYaml .Values.nsenter.resources | trim | indent 12 }}
          securityContext:
            privileged: true
      containers:
        - name: shell
          image: "{{ .Values.registry }}/{{ .Values.repository }}:{{ .Values.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1048Mi"
          command: ["sleep 7200"]
      volumes:
        - name: host-ca-certs
          hostPath:
            path: /usr/local/share/ca-certificates
            type: Directory
{{- if .Values.custom_certs.enabled }}
        - name: configmap-custom-certs
          configMap:
            name: node-configurator-custom-certs
{{- end }}
